#### general settings
name: mix_wsharp
use_tb_logger: true
model: image_base
distortion: deblur
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: mix
    mode: mix
    interval_list: [1]
    dataroots_HQ: ['datasets/REDS/train_sharp_wval.lmdb', 'datasets/GOPRO/train_sharp.lmdb']
    dataroots_LQ: ['datasets/REDS/train_blur_wval.lmdb', 'datasets/GOPRO/train_blur_linear.lmdb']
    dataset_weights: [1, 10]
    cache_keys: ~

    N_frames: 1
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 16
    HQ_size: 256
    LQ_size: 256
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
KernelWizard:
  input_nc: 3
  nf: 64
  front_RBs: 10
  back_RBs: 20
  N_frames: 1
  kernel_dim: 512
  use_vae: false
  KernelExtractor:
    norm: none
    use_sharp: true
    n_blocks: 4
    padding_type: reflect
    use_dropout: false
  Adapter:
    norm: none
    use_dropout: false

#### path
path:
  pretrain_model_G: ~
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-8

  pixel_criterion: cb
  pixel_weight: 1.0
  kernel_weight: 0.1
  gradient_loss_weight: 0.3
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 5000
